"""
train_detector.py — Train a lightweight CNN beacon detector and export to ONNX.

This script trains a small convolutional neural network on synthetic frames
generated by generate_training_data.py. The trained model is exported to ONNX
for use with the AIDetector class.

Usage:
    # Step 1: Generate training data
    python generate_training_data.py --output training_data --frames 5000

    # Step 2: Train and export
    python train_detector.py --data training_data --output models/beacon_detector.onnx

Requirements:
    - PyTorch (for training): pip install torch
    - Generated training data from generate_training_data.py

Note: PyTorch is only needed for training. Inference uses ONNX Runtime.
"""

import json
import os
import sys
import argparse
import numpy as np
from pathlib import Path

try:
    import torch
    import torch.nn as nn
    import torch.optim as optim
    from torch.utils.data import Dataset, DataLoader
    HAS_TORCH = True
except ImportError:
    HAS_TORCH = False

try:
    import cv2
    HAS_CV2 = True
except ImportError:
    HAS_CV2 = False


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------

class BeaconDataset(Dataset):
    """PyTorch dataset for labeled beacon frames."""

    def __init__(self, frames_dir: str, labels_path: str,
                 input_size: tuple = (128, 128)):
        """
        Args:
            frames_dir: Directory containing frame JPEGs.
            labels_path: Path to labels.json from generate_training_data.py.
            input_size: (H, W) to resize frames to for training.
        """
        with open(labels_path, 'r') as f:
            self.labels = json.load(f)

        self.frames_dir = frames_dir
        self.input_size = input_size

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        label = self.labels[idx]
        img_path = os.path.join(self.frames_dir, label['image'])

        # Load as grayscale
        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        if img is None:
            # Return a blank image if load fails
            img = np.zeros(self.input_size, dtype=np.uint8)

        # Resize
        img = cv2.resize(img, (self.input_size[1], self.input_size[0]))

        # Normalize to [0, 1]
        img = img.astype(np.float32) / 255.0

        # Add channel dimension: (1, H, W)
        img = np.expand_dims(img, axis=0)

        # Label: 1 = beacon visible, 0 = not visible
        target = 1.0 if label.get('visible', False) else 0.0

        # Bounding box (normalized to [0, 1]) if visible
        if label.get('visible', False) and label.get('bbox'):
            bbox = label['bbox']
            # bbox = [x1, y1, x2, y2] in pixel coords
            # We need to normalize by original frame size
            # Original frame is 1280x720
            bbox_norm = [
                bbox[0] / 1280.0, bbox[1] / 720.0,
                bbox[2] / 1280.0, bbox[3] / 720.0,
            ]
        else:
            bbox_norm = [0.0, 0.0, 0.0, 0.0]

        return (
            torch.from_numpy(img),
            torch.tensor([target] + bbox_norm, dtype=torch.float32),
        )


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------

class BeaconCNN(nn.Module):
    """Lightweight CNN for beacon detection and localization.

    Architecture:
        Conv(1,16,3) -> ReLU -> MaxPool
        Conv(16,32,3) -> ReLU -> MaxPool
        Conv(32,64,3) -> ReLU -> AdaptiveAvgPool(4)
        Flatten -> FC(64*4*4, 128) -> ReLU -> Dropout(0.3)
        FC(128, 5)  # [detection_prob, x1, y1, x2, y2]

    Output: 5 values — detection probability + normalized bbox [x1,y1,x2,y2]
    """

    def __init__(self):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(1, 16, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(16, 32, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(32, 64, 3, padding=1), nn.ReLU(),
            nn.AdaptiveAvgPool2d(4),
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(64 * 4 * 4, 128), nn.ReLU(), nn.Dropout(0.3),
            nn.Linear(128, 5),  # detection + bbox
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        # Clamp bbox outputs to [0, 1]
        det = torch.sigmoid(x[:, :1])      # detection probability
        bbox = torch.sigmoid(x[:, 1:5])     # normalized bbox
        return torch.cat([det, bbox], dim=1)


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def train_model(data_dir: str, output_path: str,
                epochs: int = 20, batch_size: int = 32,
                lr: float = 1e-3, val_split: float = 0.15,
                input_size: tuple = (128, 128)):
    """Train the beacon detector and export to ONNX.

    Args:
        data_dir: Path to training data directory (from generate_training_data.py).
        output_path: Path to save the ONNX model.
        epochs: Number of training epochs.
        batch_size: Training batch size.
        lr: Learning rate.
        val_split: Fraction of data for validation.
        input_size: (H, W) input size for the model.
    """
    frames_dir = os.path.join(data_dir, 'frames')
    labels_path = os.path.join(data_dir, 'labels.json')

    if not os.path.isfile(labels_path):
        print(f"Error: labels.json not found at {labels_path}")
        print("Run generate_training_data.py first.")
        return

    # Load dataset
    dataset = BeaconDataset(frames_dir, labels_path, input_size=input_size)
    print(f"Dataset: {len(dataset)} frames")

    # Split into train/val by seed (not random frames) to prevent data leakage
    all_seeds = sorted(list(set(label['seed'] for label in dataset.labels)))
    n_val_seeds = max(1, int(len(all_seeds) * val_split))
    val_seeds = set(all_seeds[:n_val_seeds])

    train_indices = [i for i, label in enumerate(dataset.labels) if label['seed'] not in val_seeds]
    val_indices = [i for i, label in enumerate(dataset.labels) if label['seed'] in val_seeds]

    train_set = torch.utils.data.Subset(dataset, train_indices)
    val_set = torch.utils.data.Subset(dataset, val_indices)

    train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_set, batch_size=batch_size, shuffle=False)

    # Create model
    model = BeaconCNN()
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = model.to(device)
    print(f"Model on device: {device}")
    print(f"Parameters: {sum(p.numel() for p in model.parameters()):,}")

    # Loss: BCE for detection + MSE for bbox
    optimizer = optim.Adam(model.parameters(), lr=lr)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=5, factor=0.5)

    best_val_loss = float('inf')

    for epoch in range(epochs):
        # --- Train ---
        model.train()
        train_loss = 0.0
        for images, targets in train_loader:
            images = images.to(device)
            targets = targets.to(device)

            outputs = model(images)

            # Detection loss (binary cross-entropy)
            det_loss = nn.functional.binary_cross_entropy(
                outputs[:, :1], targets[:, :1]
            )
            # Bbox loss (MSE, only for positive samples)
            pos_mask = targets[:, 0] > 0.5
            if pos_mask.any():
                bbox_loss = nn.functional.mse_loss(
                    outputs[pos_mask, 1:5], targets[pos_mask, 1:5]
                )
            else:
                bbox_loss = torch.tensor(0.0, device=device)

            loss = det_loss + bbox_loss
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            train_loss += loss.item()

        # --- Validate ---
        model.eval()
        val_loss = 0.0
        val_correct = 0
        val_total = 0
        with torch.no_grad():
            for images, targets in val_loader:
                images = images.to(device)
                targets = targets.to(device)
                outputs = model(images)

                det_loss = nn.functional.binary_cross_entropy(
                    outputs[:, :1], targets[:, :1]
                )
                pos_mask = targets[:, 0] > 0.5
                if pos_mask.any():
                    bbox_loss = nn.functional.mse_loss(
                        outputs[pos_mask, 1:5], targets[pos_mask, 1:5]
                    )
                else:
                    bbox_loss = torch.tensor(0.0, device=device)
                val_loss += (det_loss + bbox_loss).item()

                # Detection accuracy
                predicted = (outputs[:, :1] > 0.5).float()
                val_correct += (predicted == targets[:, :1]).sum().item()
                val_total += targets.size(0)

        avg_train = train_loss / len(train_loader)
        avg_val = val_loss / max(len(val_loader), 1)
        val_acc = val_correct / max(val_total, 1) * 100

        scheduler.step(avg_val)

        print(f"  Epoch {epoch+1}/{epochs}  "
              f"train_loss={avg_train:.4f}  val_loss={avg_val:.4f}  "
              f"val_acc={val_acc:.1f}%")

        if avg_val < best_val_loss:
            best_val_loss = avg_val
            # Save best model as ONNX
            _export_onnx(model, output_path, input_size)

    print(f"\nModel exported to {output_path}")
    print(f"Best validation loss: {best_val_loss:.4f}")


def _export_onnx(model, output_path: str, input_size: tuple = (128, 128)):
    """Export model to ONNX format."""
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    model.eval()
    dummy = torch.randn(1, 1, input_size[0], input_size[1])
    torch.onnx.export(
        model, dummy, output_path,
        input_names=['input'],
        output_names=['output'],
        dynamic_axes={'input': {0: 'batch'}, 'output': {0: 'batch'}},
        opset_version=17,
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == '__main__':
    if not HAS_TORCH:
        print("Error: PyTorch is required for training.")
        print("Install with: pip install torch")
        sys.exit(1)
    if not HAS_CV2:
        print("Error: OpenCV is required.")
        print("Install with: pip install opencv-python")
        sys.exit(1)

    parser = argparse.ArgumentParser(
        description='Train beacon detector CNN and export to ONNX'
    )
    parser.add_argument('--data', default='training_data',
                        help='Path to training data directory')
    parser.add_argument('--output', default='models/beacon_detector.onnx',
                        help='Output ONNX model path')
    parser.add_argument('--epochs', type=int, default=20,
                        help='Training epochs (default: 20)')
    parser.add_argument('--batch-size', type=int, default=32,
                        help='Batch size (default: 32)')
    parser.add_argument('--lr', type=float, default=1e-3,
                        help='Learning rate (default: 0.001)')
    args = parser.parse_args()

    print("=" * 60)
    print("  FSOC Beacon Detector Training")
    print("=" * 60)
    train_model(
        data_dir=args.data,
        output_path=args.output,
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr,
    )
    print("=" * 60)
